# Generated by Django 5.1.4 on 2025-01-14 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard_name', models.CharField(max_length=100)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('sale_time', models.TimeField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('item_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model_group', models.CharField(max_length=100)),
                ('model_detail', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('secondary_damage', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_title_state', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_title_type', models.CharField(blank=True, max_length=50, null=True)),
                ('has_keys', models.BooleanField(default=False)),
                ('vin', models.CharField(max_length=17)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('odometer_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('drive', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cylinders', models.CharField(blank=True, max_length=20, null=True)),
                ('runs_drives', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_status', models.CharField(blank=True, max_length=50, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=50)),
                ('location_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
    ]
